spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      server: # <-- server: 추가
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway Webflux Global Filter
                preLogger: true
                postLogger: true
          routes:
            - id: first-service
              #uri: http://localhost:8081
              uri: lb://MY-FIRST-SERVICE
              predicates:
                - Path=/first-service/**
              filters:
                - CustomFilter
            - id: second-service
              #uri: http://localhost:8082
              uri: lb://MY-SECOND-SERVICE
              predicates:
                - Path=/second-service/**
              filters:
                - CustomFilter
                - name: LoggingFilter
                  args:
                    baseMessage: Hello it's Logging Filter!!!
                    preLogger: true
                    postLogger: true

server:
  port: 8000